on:
  workflow_dispatch:
  push:
    braches:
      - "main"

jobs:
  docker-ce-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker-ce-client
          file: ./Dockerfile
          push: false
